wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.33.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694555195.360444
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 2
      - 23
      4: 3.10.6
      5: 0.15.10
      6: 4.33.1
      8:
      - 1
      - 5
